import time
reminder = UserWarning("Your attendance is due in five minutes!")
import winsound
winsound.PlaySound("Attendance.wav", winsound.SND_ASYNC)
print ("Your attendance is due in five minutes!")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in four minutes and thirty seconds!")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in four minutes!")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in three minutes and thirty seconds!")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in three minutes!")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in two minutes and thirty seconds!")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in two minutes")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in one minute and thirty seconds")
time.sleep(30)
print ("Have you completed your attendance?")
print ("Your attendance is due in one minute!")
time.sleep(30)
winsound.PlaySound("Attendance.wav", winsound.SND_ASYNC)
print ("Have you completed your attendance?")
print ("Your attendance is due in thirty seconds!")
time.sleep(25)
print("5")
time.sleep(1)
print("4")
time.sleep(1)
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
print ("Please submit now, Thank You")
